// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Alphabetical_list_of_productConfiguration : IEntityTypeConfiguration<Alphabetical_list_of_product>
    {
        public void Configure(EntityTypeBuilder<Alphabetical_list_of_product> entity)
        {
            entity.ToView("Alphabetical list of products");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Alphabetical_list_of_product> entity);
    }
}
