// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Customer_and_Suppliers_by_CityConfiguration : IEntityTypeConfiguration<Customer_and_Suppliers_by_City>
    {
        public void Configure(EntityTypeBuilder<Customer_and_Suppliers_by_City> entity)
        {
            entity.ToView("Customer and Suppliers by City");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customer_and_Suppliers_by_City> entity);
    }
}
