// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Order_SubtotalConfiguration : IEntityTypeConfiguration<Order_Subtotal>
    {
        public void Configure(EntityTypeBuilder<Order_Subtotal> entity)
        {
            entity.ToView("Order Subtotals");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order_Subtotal> entity);
    }
}
