// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Order_Details_ExtendedConfiguration : IEntityTypeConfiguration<Order_Details_Extended>
    {
        public void Configure(EntityTypeBuilder<Order_Details_Extended> entity)
        {
            entity.ToView("Order Details Extended");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order_Details_Extended> entity);
    }
}
