// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Orders_QryConfiguration : IEntityTypeConfiguration<Orders_Qry>
    {
        public void Configure(EntityTypeBuilder<Orders_Qry> entity)
        {
            entity.ToView("Orders Qry");

            entity.Property(e => e.CustomerID).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Orders_Qry> entity);
    }
}
