// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Product_Sales_for_1997Configuration : IEntityTypeConfiguration<Product_Sales_for_1997>
    {
        public void Configure(EntityTypeBuilder<Product_Sales_for_1997> entity)
        {
            entity.ToView("Product Sales for 1997");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product_Sales_for_1997> entity);
    }
}
