// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Quarterly_OrderConfiguration : IEntityTypeConfiguration<Quarterly_Order>
    {
        public void Configure(EntityTypeBuilder<Quarterly_Order> entity)
        {
            entity.ToView("Quarterly Orders");

            entity.Property(e => e.CustomerID).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Quarterly_Order> entity);
    }
}
