// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Sales_by_CategoryConfiguration : IEntityTypeConfiguration<Sales_by_Category>
    {
        public void Configure(EntityTypeBuilder<Sales_by_Category> entity)
        {
            entity.ToView("Sales by Category");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Sales_by_Category> entity);
    }
}
