// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Sales_Totals_by_AmountConfiguration : IEntityTypeConfiguration<Sales_Totals_by_Amount>
    {
        public void Configure(EntityTypeBuilder<Sales_Totals_by_Amount> entity)
        {
            entity.ToView("Sales Totals by Amount");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Sales_Totals_by_Amount> entity);
    }
}
