// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DatabaseFirst.Contexts.Configurations
{
    public partial class Summary_of_Sales_by_QuarterConfiguration : IEntityTypeConfiguration<Summary_of_Sales_by_Quarter>
    {
        public void Configure(EntityTypeBuilder<Summary_of_Sales_by_Quarter> entity)
        {
            entity.ToView("Summary of Sales by Quarter");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Summary_of_Sales_by_Quarter> entity);
    }
}
