// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseFirst.Contexts.Configurations;
using DatabaseFirst.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace DatabaseFirst.Contexts;

public partial class NorthwindContext : DbContext
{
    public NorthwindContext()
    {
    }

    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alphabetical_list_of_product> Alphabetical_list_of_products { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Category_Sales_for_1997> Category_Sales_for_1997s { get; set; }

    public virtual DbSet<Current_Product_List> Current_Product_Lists { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerDemographic> CustomerDemographics { get; set; }

    public virtual DbSet<Customer_and_Suppliers_by_City> Customer_and_Suppliers_by_Cities { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Order_Detail> Order_Details { get; set; }

    public virtual DbSet<Order_Details_Extended> Order_Details_Extendeds { get; set; }

    public virtual DbSet<Order_Subtotal> Order_Subtotals { get; set; }

    public virtual DbSet<Orders_Qry> Orders_Qries { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Product_Sales_for_1997> Product_Sales_for_1997s { get; set; }

    public virtual DbSet<Products_Above_Average_Price> Products_Above_Average_Prices { get; set; }

    public virtual DbSet<Products_by_Category> Products_by_Categories { get; set; }

    public virtual DbSet<Quarterly_Order> Quarterly_Orders { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<Sales_Totals_by_Amount> Sales_Totals_by_Amounts { get; set; }

    public virtual DbSet<Sales_by_Category> Sales_by_Categories { get; set; }

    public virtual DbSet<Shipper> Shippers { get; set; }

    public virtual DbSet<Summary_of_Sales_by_Quarter> Summary_of_Sales_by_Quarters { get; set; }

    public virtual DbSet<Summary_of_Sales_by_Year> Summary_of_Sales_by_Years { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Territory> Territories { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseLazyLoadingProxies(false).UseSqlServer("Data Source=.;Initial Catalog=Northwind;Integrated Security=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.Alphabetical_list_of_productConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Category_Sales_for_1997Configuration());
        modelBuilder.ApplyConfiguration(new Configurations.Current_Product_ListConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomerDemographicConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Customer_and_Suppliers_by_CityConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmployeeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.InvoiceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Order_DetailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Order_Details_ExtendedConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Order_SubtotalConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Orders_QryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Product_Sales_for_1997Configuration());
        modelBuilder.ApplyConfiguration(new Configurations.Products_Above_Average_PriceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Products_by_CategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Quarterly_OrderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RegionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Sales_Totals_by_AmountConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Sales_by_CategoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Summary_of_Sales_by_QuarterConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.Summary_of_Sales_by_YearConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TerritoryConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
